version: '{build}'
os: Visual Studio 2015

environment:
  ANDROID_HOME: C:\Program Files (x86)\Android\android-sdk

before_build:
 # - echo y | "%ANDROID_HOME%\tools\android.bat" --silent update sdk --no-ui --all --filter android-19
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t build-tools-19.0.0

build_script:
  - mvn clean install -P 'guice' -V

# build: off